[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NEXT_PUBLIC_SUPABASE_URL = ""
  NEXT_PUBLIC_SUPABASE_ANON_KEY = ""
  NEXT_PUBLIC_REVENUECAT_API_KEY = ""

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 